### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by zhongying1995** [sumneko/w3x2lni#11]
在解包地图成lni时，能不能把map文件夹里面的关于地形啊这些东西，放在给根目录的.w3x地图里面？这样就可以直接对.w3x地图进行地形编辑，而不用把lni转为obj，改好地形再转回来。虽然过程很快

**Comment by sumneko** [comment]
.w3x是一个特殊的文件，用来标识lni格式，你不可以修改他。
ydwe之后会支持通过.w3x直接打开lni格式地图(就像现在可以直接对.w3x右键测试)，这个功能应该可以满足你的需求。
