### ISSUE TITLE
obj2lni建议

### ISSUE THREAD

**Issue by FakedWeiss** [sumneko/w3x2lni#12]
能不能给obj转lni添加一个选项，只输出地形文件。
这样就可以做到不关闭ydwe，随时将ydwe里面的地形改动覆盖到lni里面，lni里面更改物编、代码、导入文件以及测图的过程也就更连续不会被打断。

**Comment by actboy168** [comment]
你不需要被打断，lni地图的最大作用是和版本管理工具配合。传统的w3x地图，你只能维持一个版本，而lni地图你可以有任意个版本，只需要在需要的时候借助版本管理工具把不同的版本合并即可。

回到你的问题，你可以有个一个地形的版本，它以w3x的形式存在并用ydwe编辑；同时有一个物编和代码的版本，它以lni的形式存在并用文本工具编辑。大多数时候你并不需要让这两个地图保持一致，只需要在某个时间把他们转为lni地图并合并即可。
