### ISSUE TITLE
疑似SLK优化修改了一些技能ID导致地图不正确工作

### ISSUE THREAD

**Issue by yatyricky** [sumneko/w3x2lni#23]
## before

链接: https://pan.baidu.com/s/17-fCIwbdufFcpDTis0xb3w 密码: hinj

## after

链接: https://pan.baidu.com/s/1MMEPs_rNK_oZUhr3LCyqag 密码: whpi

## 一些说明

物编中每一个单位都是1HP

地图中创建单位的时候会为其添加 +1 +2 +4 +8 …… HP 的技能

原图中你进去选择一个英雄，会发现生命值是正常的。优化之后选择英雄，生命值不正常了，看上去缺失了一些技能ID。

**Comment by actboy168** [comment]
我猜是因为你动态计算了技能的ID，没有强制引用。从而被w2l简化了它。

**Comment by sumneko** [comment]
你可以在脚本里写一个无用函数，在里面提一下你需要保留的对象ID。当然写插件也是一个不错的选择。

**Comment by actboy168** [comment]
插件是一种方法，另一种方法是你直接在代码里把要用的id都列一边。

https://github.com/actboy168/YDWE/blob/master/Development/Component/ui/ydwe/jass/YDWEGeneralBounsSystem.j#L75-L146

**Comment by yatyricky** [comment]
我选择罗列出来，免得以后更新技能了忘了更新插件
