### ISSUE TITLE
War3版本相关的数据是否不应该进入git版本管理

### ISSUE THREAD

**Issue by yatyricky** [sumneko/w3x2lni#25]
比如我 w2l mpq <path> 之后

发生了如下变化 

https://github.com/yatyricky/w3x2lni/commit/0bf3aa167aa7a606bc6c2f843f3d933e0f95aa63

**Comment by actboy168** [comment]
如果你打算把w2l当作地图代码的一部分，你应该使用地图内配置，从而避免对全局配置表的修过。template目录本身对w2l没有用，你可以忽略它。
