### ISSUE TITLE
W3x2lni和YDWE生成OBJ模式的地图无法被其他工具修改,只能读取不能写入

### ISSUE THREAD

**Issue by luciouskami** [sumneko/w3x2lni#31]
如题，虽然不是什么大问题，但还是希望修正

**Comment by luciouskami** [comment]
问题好像有点复杂，先关闭。找到确切问题再报告。

**Comment by luciouskami** [comment]
发现了，错误的ini文件确实是之前使用了旧版本导致的，然后使用YDWE，确切地说是使用w2l的地图文件均无法被其他工具修改。可能是SFMPQ这个插件的问题，希望排查一下。

**Comment by actboy168** [comment]
我认为这是你的工具/库的问题，不是w2l的问题

**Comment by luciouskami** [comment]
@actboy168  可是连万能的火龙也操作不了了，之前记得有个人说WC也不能写入数据，这次是香肠的编译器加上火龙都不行，然后我就感觉有点严重了，我想这个锅是不是该甩给stormlib？

**Comment by actboy168** [comment]
如果你有魔兽可用w2l无法使用的mpq，我会解决。同理，这个问题你应该去找对应的工具的作者解决。

**Comment by luciouskami** [comment]
@actboy168 那边我也有说，事实上测试的情况是用原版we另存为一次就行了，等下去对比一下文件看差了些什么。

**Comment by actboy168** [comment]
Fixed in 16c31b46ff74e53ef54c47885311fd8f70f1006f
