### ISSUE TITLE
w3x2lni能否提供通过【命令行】单独解析 单位、物品、技能等数据的支持？

### ISSUE THREAD

**Issue by LazyKnightX** [sumneko/w3x2lni#34]

**Comment by actboy168** [comment]
和 #9 重复

严格来说，slk数据是一个整体，单独看待某一类的做法是错误的。换句话说，不存在正确的单独解析某一类数据的方法。

**Comment by LazyKnightX** [comment]
是的，在这种情况下提供源数据链接呢？
比如解析一个 a.w3x ，反推回去出现

```
单独地图.w3x -> 战役.w3n -> war3patch.mpq -> War3xLocal.mpq -> War3x.mpq -> War3.mpq
```

即如果要着手做这方面开发的话，可否指引一下应该从本项目的哪个嵌入点开始着手？

**Comment by actboy168** [comment]
@LazyKnightX 不要讨论脱离主题的内容，如果你有其它问题，请去别的issue询问或者开新的issue

**Comment by LazyKnightX** [comment]
@actboy168 抱歉，收到，不过关于命令行指令的问题仍然有效：

```
w3x2lni_shell.exe "Campaign/战役.w3n" "02.w3n"
```

对应读取方向：

```
单独地图.w3x -> 战役.w3n -> war3patch.mpq -> War3xLocal.mpq -> War3x.mpq -> War3.mpq
```

**Comment by sumneko** [comment]
和战役无关，slk数据本身就是多类型合并在一起的，没法单独解析

**Comment by LazyKnightX** [comment]
了解了，谢谢回答。

**Comment by zqq90** [comment]
@sumneko
我的目的只是希望得到物品信息
此前，我是使用 MPQ 把所有的 war3campaign.* 重命名成 war3map.*
然后就可以转 Lni 了

**Comment by sumneko** [comment]
@zqq90 已经解释过了，需要多个文件才能转换一个文件，所以不如全部转换后自己找需要的结果。没有支持战役的计划。
