### ISSUE TITLE
wiki页面直接隐藏？

### ISSUE THREAD

**Issue by LazyKnightX** [sumneko/w3x2lni#39]
能否临时打开一下？（5分钟）
刚才已经添加了一点内容了，如果不愿意托管在github，我自己移动到别的地方去。

**Comment by sumneko** [comment]
我们项目的wiki不是用来给你打广告，宣传你自己的网站的

**Comment by LazyKnightX** [comment]
你这话让我忍不住想骂你。

你看到我在贵项目维基页面有哪半个链接是指向这个项目页面以外的地方的？
以及我有哪个地方是有一丁点涉及到广告的？

**Comment by sumneko** [comment]
@LazyKnightX 
抱歉，可能是我看错了。

**Comment by LazyKnightX** [comment]
@sumneko 如果贵项目不愿意托管wiki，请临时将我的数据复制出来，我不会再打扰贵项目半点。

**Comment by LazyKnightX** [comment]
已复制，谢谢。

**Comment by sumneko** [comment]
你wiki里错误太多了

**Comment by LazyKnightX** [comment]
@sumneko 全部整理自目前的issue，并且多为直接链接到各issue的链接。

如果是错误，目前项目并没有提供编写规范。

如果提供规范文档，我很乐意遵守。

**Comment by sumneko** [comment]
举个例子，你以一个很老的已关闭的issue作为参考写了一个条目，但实际上这个issue已经没有时效了。
