### ISSUE TITLE
转换后卡在地图配置这里

### ISSUE THREAD

**Issue by qq1053831109** [sumneko/w3x2lni#43]
使用版本2.4.6 ！转换后卡在地图配置这里！就用的普通的转到LNI再转回OBJ 然后就无法保存！

**Comment by sumneko** [comment]
请把地图发来

**Comment by yukk670** [comment]
我也碰到了这个问题！但是奇怪的是：我前段时间对相同的一个地图转lni在转回obj，打开ydwe可以完美保存！但是昨天开始无法转了，卡在地图配置里，然后生成一个缓存的文件夹不动了，哪怕我用最早的那个地图也不行！是不是因为我的魔兽出了问题要新下个？还是说我硬盘处理速度不行，完成不了大文件了？

**Comment by sumneko** [comment]
有问题的地图发给我看一下 QQ 76196625
