### ISSUE TITLE
Slk export error with 'Optimize JASS' due to new natives

### ISSUE THREAD

**Issue by jhughes** [sumneko/w3x2lni#44]
I am exporting my map as Slk with `Optimize JASS` option selected. It causes an error because my code uses new 'Blz' natives from wc3 1.29.
![slkerror](https://user-images.githubusercontent.com/591756/52161072-612e5900-2674-11e9-9556-be6b9b2bee59.png)

It would be nice to support the new natives so I can use Optimize JASS. List is here: https://gist.github.com/TinkerWorX/eee662109a95cc30d4bc7972dbeafbb2

**Comment by sumneko** [comment]
Drag your WC3 folder in to export data.
