### ISSUE TITLE
似乎导出时有些情况下会丢失技能名称丢失

### ISSUE THREAD

**Issue by seekerlee** [sumneko/w3x2lni#48]
我用的版本 2.5.1 从 hiveworkshop 下载的。重现：

1. 导出地图为 Lni 格式
问题：导出后形成的 ability.ini 文件中的很多技能的名字已经变成了：Name = ""

经检查，英文名技能没有影响。中文名中如果带有英文括号，那么括号以及括号中的文字没有影响，例如：天谴(主动)，导出后会变成 (主动)

如果已经修复了，请直接关闭。我等新版。

**Comment by sumneko** [comment]
有演示地图吗？
