### ISSUE TITLE
请问使用 slk 打包地图如何把 scripts 里的 lua 脚本一起打包进去

### ISSUE THREAD

**Issue by hongtaoStudio** [sumneko/w3x2lni#49]
直接下载英萌项目 slk 后，同样没有找到外部导入的 lua 脚本，使用 ShadowEditor 查看

**Comment by sumneko** [comment]
默认选项下 slk 后的地图会移除文件列表，因此使用mpq工具无法查看到地图中的所有文件，实际上已经打包进去了。

**Comment by hongtaoStudio** [comment]
但是把 slk 后的地图文件拿出来联网测试，其他人却是没有加载到lua脚本

**Comment by sumneko** [comment]
如果你能加载到别人却加载不到lua，说明别人使用的魔兽环境不支持lua

**Comment by hongtaoStudio** [comment]
我认为 slk 之后还是在引用本地的脚本，当我把项目的 scripts 文件夹重命名后，我进入游戏时脚本也失效了

**Comment by sumneko** [comment]
默认是会打包进去的，你为什么没打包进去不清楚
