### ISSUE TITLE
建议增加特性：Lni 增量合并

### ISSUE THREAD

**Issue by LazyKnightX** [sumneko/w3x2lni#50]
示例，假设单位写法如下：

```ini
[hfoo]
_parent = "hfoo"
Name = "步兵a"

[hfoo]
Description = "awesome"
```

目前在合并为obj后仅会留下 Description 的数据。
建议增加增量模式，使得上述 hfoo 在合并后能够保留原来的Name和新增的Description。

**Comment by sumneko** [comment]
你可以自己写一个插件来实现（on_full 时读取本地文件，然后用lni解析指定文件，遍历合并slk数据）
