### ISSUE TITLE
map\table\ 不支持.initconfig

### ISSUE THREAD

**Issue by w4454962** [sumneko/w3x2lni#51]
由于要批处理生成部分物编，又不影响原本的，需要支持多文件合并。

**Comment by w4454962** [comment]
可以给子文件的数据对象增加一个 相对路径的字段，重新保存地图时 根据相对路径存放数据。

**Comment by sumneko** [comment]
你可以自己制作一个插件，在 `on_convert` 事件中重载 `w2l:file_load` 函数，当试图读取 `table` 类型的文件时，进行自己的处理。
