### ISSUE TITLE
大佬求助  vscode 'luamake'

### ISSUE THREAD

**Issue by rb0828** [sumneko/w3x2lni#53]
'luamake' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

找不到luamake文件编不过去啊

**Comment by luciouskami** [comment]
很显然，你缺少luamake构建工具。
到actboy168的git仓库下找到luamake项目按照提示构建，然后将生成的二进制文件所在的目录加入环境变量“PATH”中，重启vscode，打开本项目，选择“编译C++代码”，然后点击发布中文/英文版，就可以构建本项目。
