### ISSUE TITLE
How to keep .wpm in obj mode?

### ISSUE THREAD

**Issue by RobinKa** [sumneko/w3x2lni#54]
Hey, thanks for your awesome tool. I was wondering how it would be possible to keep the `war3map.wpm` when building a `.w3x` in `Obj` mode. I need this because our script uses a jasshelper  preprocessor external that makes use of it and doesn't work without it.

(eg. `//! external PathMapper Oaby 48` gives error `Could not open war3map.wpm in <map/path.w3x>`)

**Comment by sumneko** [comment]
It should not drop `war3map.wpm` when converting into 'Obj'. Is `map\war3map.wpm` exists in your `Lni` map folder?

**Comment by RobinKa** [comment]
You are right the `.w3x` does indeed contain `war3map.wpm`. The issue must be something else.
