### ISSUE TITLE
Custom units are invisible in SLK mode

### ISSUE THREAD

**Issue by RobinKa** [sumneko/w3x2lni#63]
After your recent fix the standard units placed on the map were visible again. However custom units are still invisible. I made a custom unit based off of a peasent in the attached map file and it is invisible ingame.

Check on the minimap here, there are 3 units (the custom peasents) that are not visible.
![image](https://user-images.githubusercontent.com/2614101/74164872-4219be00-4c1c-11ea-8901-1bbc0ee254ed.png)

The map and its slk version (same as on the previous issue but with some custom peasents)
[customunit.zip](https://github.com/sumneko/w3x2lni/files/4181698/customunit.zip)

Also thanks for all your work, your tool is great! We're using it for building Warlock.

**Comment by sumneko** [comment]
Please check if it works.

**Comment by RobinKa** [comment]
Works in both this test map and Warlock now, thank you!
