### ISSUE TITLE
拖拽地图功能失效

### ISSUE THREAD

**Issue by luciouskami** [sumneko/w3x2lni#64]
在win8 及以上系统，在启用用户账户控制（UAC）的情况下以非管理员权限运行w3x2lni会导致拖拽地图功能失效。
问题已经找到解决方案，测试后提交PR。

**Comment by sumneko** [comment]
需要窗口管理器的权限大于等于软件的权限，才能把文件拖进去

**Comment by luciouskami** [comment]
> 需要文件管理器的权限大于等于软件的权限，才能把文件拖进去

推了PR，应该没问题了。
