### ISSUE TITLE
勾选混淆脚本时会混淆InitCustomTeams等函数会导致平台二级界面和进游戏以后的队伍设置错乱

### ISSUE THREAD

**Issue by luciouskami** [sumneko/w3x2lni#66]
如题，勾选混淆队伍时会混淆InitCustomTeams,InitCustomPlayerSlots
导致平台二级界面和进游戏以后的队伍设置错乱。
建议混淆时排除这两个函数。

**Comment by sumneko** [comment]
魔兽可以正常识别，平台识别错误那么显然是平台自己的bug

**Comment by luciouskami** [comment]
> 魔兽可以正常识别，平台识别错误那么显然是平台自己的bug

确实拉胯，不止是这两个函数的问题，我真不知道他们的局域网界面是怎么搞的，只能先忽略。
