### ISSUE TITLE
2.7.2 移除未引用ID会导致商店的选择单位(选择英雄)技能丢失图标和技能位置 (Aneu Ane2)

### ISSUE THREAD

**Issue by liehun10086** [sumneko/w3x2lni#88]
重现方法：
1.新建地图
2.摆放地精商店
3.保存
4.直接测试，选择单位位置和图标正常
5.使用2.7.2版本进行优化，勾选移除未引用ID，选择单位图标丢失

已经尝试使用引用声明的插件保持引用，且确认slk之后导出的slk图标和说明是存在的，但游戏中仍显示图标丢失

使用2.5.3旧版本无问题，不勾选移除未引用ID无问题

**Comment by liehun10086** [comment]
对比新旧版本优化器后，发现2.7.2版本优化后缺少 Units\ItemAbilityStrings.txt 文件，从旧版本slk后的地图中解包一份该文件导入，即可正常显示

**Comment by liehun10086** [comment]
[Commit 不需要简化 txt 了](https://github.com/sumneko/w3x2lni/commit/35142751f28a4098c157f70e06aa0f51df53a822)
注释这块代码后正常

**Comment by liehun10086** [comment]
排查后，发现移除 Units\ItemAbilityStrings.txt 中的 [anei]，就会导致商店的选择单位图标丢失

**Comment by sumneko** [comment]
https://github.com/sumneko/w3x2lni/blob/master/script/core/slk/backend_mark.lua
加到白名单里试试

**Comment by liehun10086** [comment]
> https://github.com/sumneko/w3x2lni/blob/master/script/core/slk/backend_mark.lua 加到白名单里试试

1. anei 的分类不是 ability，在 slk.ability 中找不到，直接引用会多一个“**引用未分类对象**”异常，需要在 backend_mark.lua 的 mustuse 表中新增一个txt表
2. 同时需要在 backend.lua 的 mustuse 中新增一个txt表
3. 在 backend_extra_txt.lua 的 make_marked_ids 方法中，遍历的 type_list 需要添加 txt 表，没有的话即使是引用了，mark也不会生效

问题解决

**Comment by sumneko** [comment]
提个PR
