### ISSUE TITLE
Buff missing art when converting to slk to obj

### ISSUE THREAD

**Issue by juvian** [sumneko/w3x2lni#93]
Leaving reduced map for easier debugging: https://drive.google.com/file/d/1gvtRDn62GxSFNqltAfV-KHaSGnwA2BW9/view?usp=sharing

There is an ability A0C0 that uses a buff B00R which works fine in slk version but when converting to obj, buff breaks and shows the tooltip missing art.
![image](https://user-images.githubusercontent.com/5660396/170761900-eacaaa48-ed2e-4512-aeeb-c4894c4913ec.png)
![image](https://user-images.githubusercontent.com/5660396/170761936-218b2bb9-c374-4f5f-ae85-88ed6b6fba7b.png)

I can see that B00R is mentioned in Units\CommonAbilityStrings.txt and don't notice anything different in war3map.w3h. Any idea what could be wrong?

**Comment by sumneko** [comment]
I have checked `w3a` and `w3h`, but did not found anything wrong.
Please try to open the map in WE and check if it normal.

**Comment by juvian** [comment]
It was a bug in my own translation tool, sorry for the trouble

**Comment by luciouskami** [comment]
> It was a bug (臭虫) in my own translation (翻译) tool (工具) , sorry (抱歉) for the trouble

guess you replace the [xxxxx]

**Comment by juvian** [comment]
> guess you replace the [xxxxx]

https://github.com/juvian/wc3-translate/commit/d2bf690804f5c6e55249c2ddf6e9b7522b5f45f5
Didn't have the w3h file there so it was not being included in the translated map
