### ISSUE TITLE
最近莫名其妙就报毒了

### ISSUE THREAD

**Issue by luciouskami** [sumneko/w3x2lni#94]
现在某数字是落地就杀，挺怪的，明明代码都没啥问题

**Comment by sumneko** [comment]
不清楚，我用的电脑管家。
不过理论上确实可以执行任意命令，挺难判别的吧。

**Comment by luciouskami** [comment]
> 不清楚，我用的电脑管家。 不过理论上确实可以执行任意命令，挺难判别的吧。

已经反映过了误报，本身也没啥敏感行为，不明白为啥会报毒，虽然是理论上确实可以执行任意命令，但是实际上也没做。

**Comment by luciouskami** [comment]
> 不清楚，我用的电脑管家。 不过理论上确实可以执行任意命令，挺难判别的吧。

目前我的想法就是加个签名，不过可能sandbox要严格一些，限制一下执行除了w2l以外的其他指令，不然也怕被利用。

**Comment by luciouskami** [comment]
@sumneko 找到问题了，原因是有的作者电脑感染了蠕虫病毒，导致w3x2nl也被感染，同时生成的地图也被感染，故被杀毒软件标记。
